### ISSUE TITLE
Create a list of actors and directors

### ISSUE THREAD

**Issue by DaveGerrardDMU** [DMU-CTEC2902/TeamArrow#4]
Create a list of the main actors (not all of them) and the directors of the Jurassic Park films.

Just the main actors: e.g. Jeff Goldbum, Richard Attenborough, Vince Vaughan.

And the Directors - Spielberg etc.

Put them in an Excel spreadsheet to start with. They'll need names, dates of birth, country they live in. Some of them will need dates of death, too.

This is a sub-task of Issue #3 .

**Comment by VijayModhwadia** [comment]
[Actors and Directors of Jurassic Park franchise.xlsx](https://github.com/DMU-CTEC2902/TeamArrow/files/132307/Actors.and.Directors.of.Jurassic.Park.franchise.xlsx)
